common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from polls1 import views



app_name = 'polls1'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls1/', include('polls1.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

polls1/urls.py
from django.urls import path

from . import views

app_name = 'polls1'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.detail, name='detail'),
    path('read/create/<int:book_id>/', views.read_create, name='read_create'),
    path('book/create/', views.book_create, name='book_create'),
    path('book/modify/<int:book_id>/', views.book_modify, name='book_modify'),
    path('book/delete/<int:book_id>/', views.book_delete, name='book_delete'),
    path('read/modify/<int:read_id>/', views.read_modify, name='read_modify'),
    path('read/delete/<int:read_id>/', views.read_delete, name='read_delete'),
]

common/models.py
from django.db import models

# Create your models here.

polls1/models.py
from pickle import TRUE

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Book(models.Model):
    objects = None
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=TRUE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()


class Read(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=TRUE)
    create_date = models.DateTimeField()

    @property
    def __str__(self):
        return self.subject

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

polls1/forms.py
from django import forms
from polls1.models import Book, Read


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class ReadForm(forms.ModelForm):
    class Meta:
        model = Read
        fields = ['content']
        labels = {
            'content': '후기',
        }

common/views.py
# Create your views here.

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

polls1/views.py
# Create your views here.

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Book
from .forms import BookForm, ReadForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):
    page = request.GET.get('page', '1')
    book_list = Book.objects.order_by('-create_date')
    paginator = Paginator(book_list, 3)
    page_obj = paginator.get_page(page)
    context = {'book_list': page_obj}
    return render(request, "polls1/book_list.html", context)


def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    context = {'book': book}
    return render(request, 'polls1/book_detail.html', context)


@login_required(login_url='common:login')
def read_create(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == "POST":
        form = ReadForm(request.POST)
        if form.is_valid():
            read = form.save(commit=False)
            read.author = request.user
            read.create_date = timezone.now()
            read.book = book
            read.save()
            return redirect('polls1:detail', book_id=book.id)
    else:
        form = ReadForm()
    context = {'book': book, 'form': form}
    return render(request, 'polls1/book_detail.html', context)


@login_required(login_url='common:login')
def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.author = request.user
            book.create_date = timezone.now()
            book.save()
            return redirect('polls1:index')
    else:
        form = BookForm()
    context = {'form': form}
    return render(request, 'polls1/book_form.html', context)


@login_required(login_url='common:login')
def book_modify(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.user != book.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('polls1:detail', book_id=book.id)

    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.author = request.user
            book.modify_date = timezone.now()
            book.save()
            return redirect('polls1:detail', book_id=book.id)
    else:
        form = BookForm(instance=book)
    context = {'form': form}
    return render(request, 'polls1/book_form.html', context)

templates/base.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- polls1 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>reading book</title>
</head>
<body>
<!-- nav -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'polls1:index' %}">Book</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (logout)</a>
    {% else %}
    <a class="nav-link" href="{% url 'common:login' %}">login</a>
    {% endif %}
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/polls1/book_detail.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ book.subject }}</h2>
    <div style="white-space: pre-line;">{{ book.content }}</div>
    <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2 text-left">
            {{ book.author.username }}
        </div>
        <div class="badge badge-light p-2 text-left">
            {{ book.create_date }}
        </div>
    </div>
        {% if request.user == book.author %}
        <div class="my-3">
            <a href="{% url 'polls1:book_modify' book.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
        </div>
        {% endif %}
    <h5 class="border-bottom my-3 py-2">{{ book.read_set.count }}개의 후기가 있습니다.</h5>
    {% for read in book.read_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ read.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    <div class="mb-2">{{ read.author.username }}</div>
                    <div> {{ read.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
    <form action="{% url 'polls1:read_create' book.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
{% endblock %}
</div>

templates/polls1/book_form.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}
<div class="container">
    <h3 class="my-3 border-bottom pb-2">질문등록</h3>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/polls1/book_list.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}
        <div class="container my-3">
            <table class="table">
                <thead>
                <tr class="text-center thead-dark">
                    <th style="width:50%">제목</th>
                    <th>글쓴이</th>
                    <th>작성일시</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% if book_list %}
                {% for book in book_list %}
                <tr class="text-center">
                    <td class="text-center thead-dark">
                        <a href="{% url 'polls1:detail' book.id %}">{{ book.subject }}</a>
                        {% if book.read_set.count > 0 %}
                        <span class="text-danger small ml-2">{{ book.read_set.count }}</span>
                        {% endif %}
                    </td>
                    <td class="text-center thead-dark">{{ book.author.username }}</td>
                    <td class="text-center thead-dark">{{ book.create_date }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="10">질문이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>


    <ul class="pagination justify-content-center">
        {% if book_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ book_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_number in book_list.paginator.page_range %}
            {% if page_number >= book_list.number|add:-5 and page_number <= book_list.number|add:5 %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if book_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ book_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

            <a href="{% url 'polls1:book_create' %}" class="btn btn-primary">책 등록하기</a>
        </div>
{% endblock %}

templates/polls1/read_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}